[shared]
system-prompt = """
You are a clinical chart reviewer for a study examining the efficacy of various \
treatments for pediatric low-grade glioma (pLGG) across various pathological/genetic \
subtypes.
Your task is to extract patient-specific information from an unstructured clinical \
document and map it into a predefined Pydantic schema.

Core Rules:
1. Base all assertions ONLY on patient-specific information in the clinical document.
   - Never negate or exclude information just because it is not mentioned.
   - Never conflate family history or population-level risk with patient findings.
   - Do not count past medical history, prior episodes, or family history.
2. Do not invent or infer facts beyond what is documented.
3. Maintain high fidelity to the clinical document language when citing spans.
4. Answer patient outcomes with strongest available documented evidence:
5. Always produce structured JSON that conforms to the Pydantic schema provided below.

Pydantic Schema:
%JSON-SCHEMA%
"""

user-prompt = """
Evaluate the following clinical document for glioma variables and outcomes.
Here is the clinical document for you to analyze:

%CLINICAL-NOTE%
"""

models = [
    "claude-sonnet45",
    "gpt4o",
    "gpt5",
    "gpt-oss-120b",
    "llama4-scout",
]


[[task]]
name = "diagnosis"
response-schema = "glioma-diagnosis-annotation.json"
# Version History:
# ** 2 (2026-02): Updated model to include histology information
# ** 1 (2026-01): Initial version
version = 1

[[task]]
name = "document_type"
response-schema = "glioma-document-type-annotation.json"
# Version History:
# ** 1 (2026-01): Initial version
version = 1

[[task]]
name = "gene"
response-schema = "glioma-gene-annotation.json"
# Version History:
# ** 1 (2026-01): Initial version
version = 1

[[task]]
name = "medications"
response-schema = "glioma-medications-annotation.json"
# Version History:
# ** 1 (2026-01): Initial version
version = 1

[[task]]
name = "progression"
response-schema = "glioma-progression-annotation.json"
# Version History:
# ** 1 (2026-01): Initial version
version = 1

[[task]]
name = "surgical"
response-schema = "glioma-surgical-annotation.json"
# Version History:
# ** 2 (2026-02): Annotation class now has helpful description
# ** 1 (2026-01): Initial version
version = 1